version: '3.8'
services:
  db:
    container_name: pret-livres-service
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: PretLivres
    ports:
      - '5432:5432'
  pgadmin:
    container_name: pret_livres_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: draimade@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
